- pipeline: "Pipeline"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "NANO"
  cpu: "ARM"
  actions:
  - action: "npm start"
    type: "BUILD"
    docker_image_name: "library/node"
    docker_image_tag: "20"
    execute_commands:
    - "# yarn install"
    - "npm install"
    - "npm start"
    shell: "BASH"
